/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        orange: "#ed8936",
        "surface-container-highest": "#e3e2e6",
        "on-surface-variant": "#43474e",
        "inverse-primary": "#adc7f7",
        "on-secondary-container": "#004172",
        "surface-variant": "#e3e2e6",
        "on-primary-fixed": "#001b3c",
        "primary-container": "#1a365d",
        "inverse-surface": "#2f3033",
        "on-tertiary-container": "#c6955e",
        "on-primary-container": "#86a0cd",
        "on-secondary": "#ffffff",
        "surface-dim": "#dad9dd",
        "tertiary-container": "#4f2e00",
        "on-surface": "#1a1c1e",
        "outline-variant": "#c4c6cf",
        "on-tertiary-fixed": "#2b1700",
        "surface-bright": "#faf9fd",
        primary: "#002045",
        "primary-fixed": "#d6e3ff",
        error: "#ba1a1a",
        "tertiary-fixed": "#ffddba",
        surface: "#faf9fd",
        "surface-container-high": "#e9e7eb",
        tertiary: "#321b00",
        "on-tertiary": "#ffffff",
        "surface-container": "#efedf1",
        "inverse-on-surface": "#f1f0f4",
        "on-background": "#1a1c1e",
        "error-container": "#ffdad6",
        "surface-container-lowest": "#ffffff",
        "on-primary": "#ffffff",
        "surface-container-low": "#f4f3f7",
        secondary: "#0061a5",
        "on-tertiary-fixed-variant": "#633f0f",
        "on-secondary-fixed-variant": "#00497e",
        "on-primary-fixed-variant": "#2d476f",
        "secondary-container": "#66affe",
        "on-error": "#ffffff",
        "secondary-fixed": "#d2e4ff",
        background: "#faf9fd",
        "surface-tint": "#455f88",
        "primary-fixed-dim": "#adc7f7",
        outline: "#74777f",
        "on-secondary-fixed": "#001d37",
        "tertiary-fixed-dim": "#f2bc82",
        "secondary-fixed-dim": "#9fcaff",
        "on-error-container": "#93000a",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        sm: "8px",
        base: "4px",
        xs: "4px",
        gutter: "20px",
        lg: "24px",
        "container-max": "1200px",
        md: "16px",
        xl: "32px",
        xxl: "48px",
      },
      fontFamily: {
        button: ["Plus Jakarta Sans"],
        "body-md": ["Plus Jakarta Sans"],
        h3: ["Plus Jakarta Sans"],
        h1: ["Plus Jakarta Sans"],
        h2: ["Plus Jakarta Sans"],
        "body-lg": ["Plus Jakarta Sans"],
        "body-sm": ["Plus Jakarta Sans"],
        "label-caps": ["Plus Jakarta Sans"],
      },
      fontSize: {
        button: ["16px", { lineHeight: "1", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        h3: ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        h1: [
          "40px",
          { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        h2: [
          "32px",
          { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "700" },
        ],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-caps": [
          "12px",
          { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "700" },
        ],
      },
    },
  },
  plugins: [],
};
